stats = {
    "categories": [
        "Web Design",
        "Scala",
        "C#",
        "Data Analysis",
        "Ember.js",
        "ERP & CRM",
        "Microsoft",
        "Dreamweaver",
        "Python",
        "Networking & Cloud Computing",
        "JavaScript",
        "Ext JS",
        "NoSQL",
        "Windows Phone",
        "Maya",
        "jQuery",
        "Computers & Technology",
        "XML",
        "Computer Science",
        "Game Programming",
        "Cisco",
        "Linux & Unix",
        "3D Graphics",
        "Web Development",
        "Swift",
        "Marketing & SEO",
        "C & C++",
        "Messaging",
        "Services & APIs",
        "SQL",
        "Mac",
        "PostgreSQL",
        "Groovy",
        "Rails",
        "CMS",
        "Infrastructure",
        "Clojure",
        "MySQL",
        "Business Applications",
        "Software",
        "Wireless Networks",
        "Datebases",
        "PowerShell",
        "OpenCL",
        "Networks, Protocols & APIs",
        "Programming",
        "Oracle",
        "GUI",
        "Windows & PC",
        "SOA",
        "Bootstrap",
        "Delphi",
        "MongoDB",
        "Data in the Enterprise",
        "HTML, HTML5 & CSS",
        "Certification",
        "Backbone.js",
        "PHP",
        "Flash",
        "Macintosh",
        "Hardware & DIY",
        "Cloud & Virtualization",
        "Illustrator",
        "Operating Systems",
        "Office",
        "Data Processing",
        "SharePoint",
        "ActionScript",
        "Apps",
        "Graphics & Design",
        "Mail Servers",
        "Monitoring",
        "Android",
        "Network Security",
        "Data Mining",
        "3D Printing",
        "iOS",
        "AngularJS",
        "Web Servers",
        "Administration",
        "Security",
        "Java",
        "Communications",
        "Other",
        "Windows",
        "Algorithms",
        "Photoshop",
        "ASP.NET",
        "Perl",
        "Express.js",
        "Big Data",
        "Enterprise",
        "Linux",
        "Network Administration",
        "Theory",
        "CAD",
        "Front-End Frameworks",
        "Ruby",
        ".NET",
        "Visual Basic",
        "Cloud Computing",
        "Task Automation",
        "Objective-C",
        "Microsoft Platform",
        "Premiere"
    ]
}